---
title: "customer_time_series_multivariate"
output: html_notebook
---

```{r}
library(readr)
library(forecast)
combined_clean <- read_csv("C:/Users/wangka3/Desktop/learning/R_exercise2/combined_clean.csv")
```

# The attempt to use ARIMAX.
```{r}
train_data = combined_clean[1:15912, 5:58]
test_data = combined_clean[15913:17376, 5:58]
```

```{r}
model_cust = auto.arima(combined_clean$cust_168[1:15912], 
                        xreg = data.matrix(train_data))
```

```{r}
model_cust
```


```{r}
checkresiduals(model_cust)
```

### ARIMA does not capture seasonality well. Need to use another model.
```{r}
forecast_cust = forecast(model_cust, xreg = data.matrix(train_data))
(autoplot(forecast_cust))
```

# Now use msts with seasonal periods equals to 24 hours and 24 * 7 = 168 hours.
```{r}
cust <- msts(log(combined_clean$cust_168[1:15841] + 1), seasonal.periods=c(24,168))
model_cust <- tbats(cust)
(autoplot(forecast(model_cust, h = 17376 - 15841)))
```


```{r}
others <- msts(log(combined_clean$others_168[1:15841] + 1), seasonal.periods=c(24,168))
model_others <- tbats(others)
(autoplot(forecast(model_others, h = 17376 - 15841)))
```












```{r}
test <- msts(log(combined_clean$others_168[1:15912] + 1), seasonal.periods=c(24,168))
test.fit <- tbats(test)
(autoplot(forecast(test.fit, h = 2000)))
```

```{r}
test2 <- msts(log(combined_clean$cust_168[1:15841] + 1), seasonal.periods=c(24,168))
test2.fit <- tbats(test2)
(autoplot(forecast(test2.fit, h = 2000)))
```